### ISSUE TITLE
Simple cards and SSML

### ISSUE THREAD

**Issue by falent** [JargonInc/jargon-sdk-nodejs#10]
Hi, 

Im wondering how to work with SSML tags with simple card content. I need to add some SSML tags to my output and I dont want to create a new card content. I wish to use the same object as I used into speak method.

How can I remove tags from 'speak(output)' that I can use the same output object in 'withSimpleCard' method. Is it possible? Amazon refused skill certification if it has any SSML tag in simple card content and almost every time makes no sense to prepare a new output only for cards :)

`  "Stop":{
    "STOP_ANSWER":{
      "v1": "Bis zum nächsten<break time='0.5s'/> Mal!"
    }
  }`

My code 
```
   
const output = ri('Stop.STOP_ANSWER');

    const attributes = handlerInput.attributesManager.getSessionAttributes();
    attributes.state = state.closedSession;
    handlerInput.jrb.speak(output).withSimpleCard(output,output).withShouldEndSession(true);
```

**Comment by gsdriver** [comment]
The cleanest way would be to have a different entry for the displayed text, since as you're seeing the text you want to display *is* different than the content you want to speak.  This would also allow you to deviate further if, for example, you wanted to change the spelling of the output speech to make it sound closer to what you intended but don't want the misspellings on the screen.  

However, if you really want to keep one entry, you can use a regular expression to remove the SSML tags like this: `output.replace(/<\/?[^>]+(>|$)/g, "")`

**Comment by falent** [comment]
but output is not a String ;) it is jargon Object so it is not so easy as you mentoned :P

**Comment by gsdriver** [comment]
Ah yes ... you could use render which will then allow you to do this `handlerInput.jrm.render(output)`

**Comment by falent** [comment]
could you help me please to do this?  

```
const output = ri('Stop.STOP_ANSWER');
const newOut = handlerInput.jrm.render(output).replace(/<\/?[^>]+(>|$)/g, "")
const attributes = handlerInput.attributesManager.getSessionAttributes();
handlerInput.jrb.speak(output).withSimpleCard(newOut ,newOut );
return handlerInput.jrb.getResponse();
```

**Comment by gsdriver** [comment]
It would be like this:

```
const output = await handlerInput.jrm.render(ri('Stop.STOP_ANSWER'));
const newOut = output.replace(/<\/?[^>]+(>|$)/g, "");
const attributes = handlerInput.attributesManager.getSessionAttributes();
handlerInput.responseBuildler.speak(output).withSimpleCard(newOut ,newOut );
return handlerInput.responseBuilder.getResponse();
```

Once you've called render, you have a string so you can manipulate it and just use the regular handlerInput.responseBuilder object.

**Comment by falent** [comment]
but newOut I have String how to use it in method withSimpleCard() when there is demanded RenderItem type

**Comment by gsdriver** [comment]
After you use render, you no longer use `handlerInput.jrb` but rather the normal ask-sdk syntax, because you have a string.  So you can just use handlerInput.responseBuilder.

**Comment by falent** [comment]
I managed :) Thanks for your help :)
