### ISSUE TITLE
How to concatenate strings from jargon?

### ISSUE THREAD

**Issue by falent** [JargonInc/jargon-sdk-nodejs#2]
Hi, it is possible to concatenate strings with jargon? It doesnt work if I try it in this way :(
It makes sense if your used can hear concatenate output because it will be always different :( With i18n something like this work. Why is it different with jargon? Is any chance to do it?

`
class LaunchRequestHandler {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
  }
  async handle(handlerInput) {

    let output = ri('HI').toString() + ri('SPACE').toString()+ri('WELCOME').toString();
    return handlerInput.jrb
        .speak(output)
        .reprompt(output)
        .getResponse();
  }
}
`

**Comment by jonburs** [comment]
There are a few different approaches to concatenating content with the Jargon SDK. Which one will be best for you depends on the specifics of your use case.

### 1. Use variables in your resource strings (https://github.com/JargonInc/jargon-sdk-nodejs/tree/master/packages/alexa-skill-sdk#named-parameters)

This works best when you need to fill static text with values. Those values can be generated within your code, or can themselves be resources (by using a RenderItem as a parameter value -- see https://github.com/JargonInc/jargon-sdk-nodejs/tree/master/packages/alexa-skill-sdk#renderitem)

### 2. Make multiple calls to speak() or reprompt(), passing in a single RenderItem to each call

As this is a non-default behavior (compared to the standard Alexa Skill Kit response builder) you need to explicitly enable it (see https://github.com/JargonInc/jargon-sdk-nodejs/tree/master/packages/alexa-skill-sdk#jargonresponsebuilder for details).

This method work best for concatenating larger pieces of content, such as sentences or paragraphs. While it works for smaller pieces of content (words or phrases), doing so can cause issues when your skill support multiple languages.

### 3. Use the lower level Jargon resource manager to render individual strings

With this approach you'd make calls into handlerInput.jrm to directly call one of the render methods (https://github.com/JargonInc/jargon-sdk-nodejs/tree/master/packages/alexa-skill-sdk#resourcemanager). Note that those methods return promises to the rendered content; async/await makes dealing with those promises much simpler.

This approach works best for merging together small snippets of content, but can cause a lot of difficulty in multi-language skills if the order of the content needs to change across languages.

Note that the return value of the ri() function is an object that's meant to be passed to one of the methods in JargonResponseBuilder or JargonResourceManager -- it contains the information needed to render content, but not the rendered content itself. This is something that we need to make clearer in our documentation, along with more guidance on how to construct and compose complex content.

Hope this helps -- please let me know if you further questions!

**Comment by falent** [comment]
Hi Jonburs, 

thank you for your help. In my case it makes no sense to use method 1. I need that jargon picks up one string from the array and get output randomly fe:
Hi What is your name?
Hello What is your name? etc

I will share with you my json language file to be better understand ;)

`
{
  "SPACE":" ",
  "HI":{
    "v1":"Hi",
    "v2":"Hello"
  },
  "WELCOME":{
    "v1":"What is your name?",
    "v2":"Tell me your name please?"
  },
}
`
I wish that jargon concatenates randomly such a sentence:
` let output = ri('HI') + ri('SPACE')+ri('WELCOME');
    return handlerInput.jrb
        .speak(output, true)
        .reprompt(item)
        .getResponse();
`
I got no response from alexa doing it in that way. I tried your second advise 
`new Jargon.JargonSkillBuilder({mergeSpeakAndReprompt: true}).wrap(Alexa.SkillBuilders.custom())`

When I debug my skill I can see under output variable:
`[object Object][object Object][object Object]`

Could you give me please an example how I can solve my probem?

Best Regards,

**Comment by jonburs** [comment]
Method 1 actually works well in this scenario, leveraging that fact that you can use a RenderItem as a parameter value:
```json
{
"SPACE":" ",
"HI":{ "v1":"Hi", "v2":"Hello" },
"WELCOME":{ "v1":"What is your name?", "v2":"Tell me your name please?" },
"Template":"{Greeting} {Question}"
}
```
```javascript
let msg = ri('Template', { Greeting: ri('HI'), Question: ri('WELCOME') })
return handlerInput.jrb.speak(msg).reprompt(msg).getResponse()
```

Method 2 would look like:
```javascript
// Assumes JargonSkillBuilder was configured with { mergeSpeakAndReprompt: true }
let messages = [ri('HI'), ri('SPACE'), ri('WELCOME')]
messages.forEach(r => {
    handlerInput.jrb.speak(r).reprompt(r)
})
return handlerInput.jrb.getResponse()
```

**Comment by TheDreamSaver** [comment]
How do we merge the responses for the Jovo plugin?

**Comment by jonburs** [comment]
For Jovo you need to either use method 1 or method 3 described above. There isn't currently support for mergeSpeakAndReprompt; various implementation details make that tricky to do.

**Comment by acerbisgianluca** [comment]
> Method 1 actually works well in this scenario, leveraging that fact that you can use a RenderItem as a parameter value:
> 
> ```json
> {
> "SPACE":" ",
> "HI":{ "v1":"Hi", "v2":"Hello" },
> "WELCOME":{ "v1":"What is your name?", "v2":"Tell me your name please?" },
> "Template":"{Greeting} {Question}"
> }
> ```

@jonburs is cross reference going to be implemented?

**Comment by jonburs** [comment]
> > Method 1 actually works well in this scenario, leveraging that fact that you can use a RenderItem as a parameter value:
> > ```json
> > {
> > "SPACE":" ",
> > "HI":{ "v1":"Hi", "v2":"Hello" },
> > "WELCOME":{ "v1":"What is your name?", "v2":"Tell me your name please?" },
> > "Template":"{Greeting} {Question}"
> > }
> > ```
> 
> @jonburs is cross reference going to be implemented?

Sorry for the slow reply on this! We're working on an updated approach to the SDK that will include cross-reference functionality. Beta versions are available at https://www.npmjs.com/package/@jargon/platform-sdk-core if you want to take an early look. We're driving to get this to 1.0.0 (and up on github with source) within the next few weeks.
