### ISSUE TITLE
resources path should be configurable

### ISSUE THREAD

**Issue by vpayette** [JargonInc/jargon-sdk-nodejs#3]
The Jargon SDK is hard-coded to only look for resources at ${cwd}/resources

It would be nice if you made this path configurable - the underlying library you rely on, i18next does:

https://github.com/JargonInc/jargon-sdk-nodejs/blob/master/packages/sdk-core/lib/resourceManager/i18next.ts#L146

(FYI, that line of code is where the resources directory is hard-coded)

**Comment by jonburs** [comment]
It would be pretty simple to allow that directory to be configurable via a new field in ResourceManagerOptions.

Out of curiosity, is there a particular reason you're looking to store the resource files in a different directory?

**Comment by vpayette** [comment]
Making it configurable would be great. The reason is that having the resources in a hard coded directory forces us to move our bespoken tests to that directory.

**Comment by jonburs** [comment]
https://www.npmjs.com/package/@jargon/alexa-skill-sdk/v/1.3.0 adds support for changing the resource directory (via ResourceManagerOptions.resourceDirectory, added in https://www.npmjs.com/package/@jargon/sdk-core/v/1.3.0)
